
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 90
#define YY_END_OF_BUFFER 91
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[257] =
    {   0,
        0,    0,   75,   75,    0,    0,   91,   89,   88,   87,
       58,   89,   76,   77,   41,   40,   80,   79,   47,   47,
       82,   78,   39,   81,   39,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   83,   84,   89,   72,   75,   74,   73,
       71,   60,   59,   70,    0,    0,    0,   86,   43,    0,
        0,    0,   47,    0,   85,   39,   42,   42,   42,    0,
       42,   42,   42,   42,   42,   42,   42,   25,   42,   42,
       42,   42,   42,   21,   36,   42,   42,   42,   42,   42,
        7,   34,   42,   42,   42,   42,   42,   29,   42,   42,

       42,   42,   42,   42,   42,   75,   73,   71,   69,   68,
       70,   65,   62,   61,   64,   63,   66,   67,    0,   57,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   49,
        0,   48,    0,   44,   44,   41,   42,   42,   42,   42,
       42,   38,   42,   42,   42,   41,   42,   42,   20,   42,
       28,   42,   42,   42,   42,   41,   18,   35,   42,   42,
       42,   42,    6,   42,   42,   42,    9,   42,   42,   42,
       56,   54,   51,   50,   53,   52,   55,    0,   43,   43,
       46,   46,   49,   45,   48,   44,   42,   42,   42,   26,
       15,   42,   42,   23,   42,   42,   42,   42,   42,    5,

       42,   42,   42,   32,   13,   42,   22,   37,    3,   42,
       31,   42,   43,    0,   46,   46,    0,    4,   19,   42,
        2,   42,   37,   42,   42,   42,   42,   42,   42,   42,
       42,   24,   33,   42,   30,   42,   42,   42,   17,   42,
       42,   42,    8,   14,   16,   42,   12,   42,   42,    1,
       10,   42,   42,   27,   11,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    5,    5,    5,    5,    7,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   17,   18,
       18,   18,   18,   18,   18,   18,   18,   19,   20,   21,
       22,   23,    5,    5,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   33,   33,   34,   35,   36,   37,   38,
       33,   39,   40,   41,   42,   43,   44,   45,   46,   33,
       47,   48,   49,    5,   50,    5,   51,   52,   53,   54,

       55,   56,   57,   58,   59,   33,   33,   60,   61,   62,
       63,   64,   33,   65,   66,   67,   68,   69,   70,   71,
       72,   33,   73,    5,   74,    5,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[75] =
    {   0,
        1,    1,    2,    3,    3,    4,    3,    3,    3,    3,
        3,    3,    3,    5,    3,    6,    7,    7,    3,    3,
        3,    3,    3,    8,    8,    8,    8,    8,    8,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    3,    4,    3,   10,
        8,    8,    8,    8,    8,    8,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    3,   11
    } ;

static const flex_int16_t yy_base[269] =
    {   0,
        0,    0,   72,   73,   74,   75,  731,  745,  745,  745,
      745,  144,  745,  745,  745,  745,  745,   68,   65,   75,
      702,  745,   65,  745,  700,   59,   76,  145,   69,  147,
      137,  663,   79,  170,   57,  173,  183,   75,   83,  134,
      195,   92,  212,  745,  745,    0,  745,    0,  745,  637,
        0,  745,  745,  275,  652,  652,  320,  745,  238,  197,
       82,  643,  247,  269,  745,  745,  604,  177,   95,    0,
      219,  209,  256,  270,  120,  180,  248,  136,  171,  265,
      234,  240,  263,  603,  262,  296,  207,  280,  297,  298,
      602,  599,  302,  301,  342,  312,  300,  598,  328,  333,

      334,   68,  336,  348,  597,    0,  571,    0,  745,  745,
      745,  745,  745,  745,  745,  745,  745,  745,  637,  745,
      636,  633,  621,  588,  577,  540,  384,  393,  161,  374,
        0,  529,  396,  745,  399,  487,  370,  481,  373,  374,
      391,  474,  394,  386,  387,  449,  390,  400,  446,  393,
      398,  412,  411,  324,  413,  436,  431,  428,  419,  434,
      443,  435,  425,  421,  439,  445,  408,  442,  451,  438,
      745,  745,  745,  745,  745,  745,  745,  490,  745,  494,
      272,  497,  501,  430,  421,  503,  476,  454,  495,  381,
      379,  484,  486,  369,  502,  504,  491,  499,  492,  325,

      496,  510,  523,  307,  293,  524,  286,  276,  258,  516,
      251,  536,  551,  523,  559,  561,  258,  202,  190,  546,
      188,  535,  185,  540,  549,  552,  551,  543,  556,  568,
      567,  169,  140,  564,  135,  577,  566,  572,  125,  580,
      573,  585,  123,  118,   87,  588,   62,  592,  586,   55,
       52,  605,  606,   47,   33,  745,  661,  672,  681,  687,
      690,  699,  709,  719,  725,  728,  732,  736
    } ;

static const flex_int16_t yy_def[269] =
    {   0,
      256,    1,  257,  257,  258,  258,  256,  256,  256,  256,
      256,  259,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  256,  256,  261,  256,  262,  256,  256,
      263,  256,  256,  264,  256,  256,  256,  256,  256,  256,
      256,  265,  256,  256,  256,  256,  260,  260,  260,  266,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,

      260,  260,  260,  260,  260,  262,  256,  263,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      267,  268,  256,  256,  256,  260,  260,  266,  260,  260,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  267,  268,  256,  260,  260,  260,  260,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,

      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  256,  256,  256,  256,  267,  260,  260,  260,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260,    0,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256
    } ;

static const flex_int16_t yy_nxt[820] =
    {   0,
        8,    9,   10,    9,    8,   11,   12,   13,   14,   15,
       16,   17,   16,   18,   15,   19,   20,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       32,   33,   32,   34,   35,   36,   37,   38,   39,   40,
       41,   32,   42,   43,   32,   32,   44,    8,   45,   46,
       26,   27,   28,   29,   30,   31,   32,   32,   33,   34,
       35,   36,   37,   38,   39,   40,   41,   32,   42,   43,
       32,   32,   47,    8,   49,   49,   52,   52,   60,   53,
       53,   58,   70,   59,   59,   59,   66,   66,   60,   61,
       63,   63,   63,   88,   68,  129,   70,   69,  130,  168,

       77,   70,   64,   71,   70,   78,   70,   84,   70,   62,
       95,   70,   72,   94,   85,  101,   61,   70,   70,   88,
       68,   54,   54,   69,   70,   70,  168,   77,   70,   64,
       71,   78,   70,  137,   84,   62,   70,   95,   72,   94,
       85,   70,  101,  144,   70,   50,   50,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,  137,
       81,   96,   55,   55,   55,   55,   55,   70,   73,   70,
      144,   74,   70,   82,   70,   75,  181,  182,   83,  147,
       79,   76,   80,   70,   70,   70,   70,   81,   96,   70,
       55,   57,   55,   55,   70,   73,   70,   86,   74,   82,

       89,   87,   75,  136,   83,  147,   79,   76,   80,   90,
      148,   91,   59,   59,   59,  145,   55,   55,   70,   70,
       70,   92,   70,   93,   86,   97,   70,   89,   87,   70,
      136,   98,   70,   99,   70,   90,  148,   70,   91,   70,
      100,  145,  102,  103,   70,  140,  155,   92,  139,   93,
      104,   70,   97,  127,   59,   59,   70,   98,   70,   99,
       60,   70,   63,   63,   63,  128,  100,  150,   70,  102,
      103,  140,  155,  217,   64,  139,  104,  109,  151,  133,
      110,  133,  141,   70,  134,  135,  135,  214,  182,   70,
      146,  149,  128,  150,  142,  143,   74,   70,  152,  112,

       70,   64,  153,  113,  151,   70,  156,   70,  142,  141,
      114,   70,   70,  115,   70,  116,  146,  117,  149,   70,
      142,  143,  118,   74,  152,   70,  112,  164,  153,   70,
      113,  154,  159,  156,  142,   70,  114,  160,  158,  115,
      157,  116,   70,  117,  121,   70,   70,   70,  122,   70,
       70,   70,  163,  199,  164,  123,   70,  154,  124,  159,
      125,   70,  126,  160,  158,  161,  157,  162,  119,  165,
      166,  121,  167,   70,   70,  122,  169,   70,  163,  170,
      199,  123,   70,   70,  124,   70,  125,  129,  126,  183,
      183,   70,  161,  187,  162,  165,  166,   70,  167,  127,

       59,   59,  169,  178,  188,  178,  170,  189,  179,  180,
      180,  134,  135,  135,  186,  186,  186,  141,   70,   70,
      187,  190,   70,   70,  191,  193,  192,  194,   70,  142,
       70,  188,  195,  189,  131,   70,   70,  197,  198,   70,
       70,  196,   70,   70,  141,  217,  201,   70,  190,   70,
      191,  193,  192,  200,  194,  142,  207,   70,  195,  202,
       70,   70,   70,  203,  197,  198,  208,  196,   70,  204,
       70,  206,  209,  201,   70,  210,  205,   70,  212,  200,
       70,  211,  207,   70,   70,   70,  202,   70,   70,  219,
      203,   70,   70,  208,   70,   70,  204,  206,   70,  209,

       70,  210,  205,   70,  212,  179,  180,  180,  211,  213,
      213,  213,  215,  216,  129,  219,  183,  183,  186,  186,
      186,  218,  220,   70,  221,   70,  222,  224,  226,  223,
       70,  225,  227,   70,  228,   70,   70,  229,  214,  182,
       70,   70,  131,  232,   70,   70,  177,  218,   70,  220,
      221,   70,  222,   70,  224,  226,  223,  225,  227,   70,
      228,  230,  231,  233,  229,   70,  213,  213,  213,  234,
      232,  235,   70,   70,  215,  215,  215,  216,  236,  238,
      237,  239,  241,  176,   70,   70,  240,  230,  231,   70,
      233,  242,   70,  243,  175,   70,  234,  235,   70,  244,

       70,   70,  246,  245,  236,   70,  238,  237,  239,  241,
      247,  248,  240,   70,  249,   70,   70,   70,  242,  250,
      243,   70,   70,  251,  253,  244,   70,  174,  246,   70,
      245,  252,  254,  255,   70,   70,  247,   70,  248,  173,
      249,   70,  172,  171,  107,  250,   70,   70,   70,  251,
      253,   70,   70,   70,   70,   70,  131,  252,  120,  254,
      255,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   67,   67,   67,   67,   67,  105,  105,  106,

      119,  106,  106,  106,  106,  106,  106,  106,  106,  108,
      107,  108,   70,  108,  108,  108,  108,  108,  108,  108,
      111,   66,  111,   65,  111,  111,  111,  111,  111,  132,
      256,  132,  132,  138,  138,  138,  138,  184,  184,  184,
      185,  185,  185,  185,    7,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,

      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256
    } ;

static const flex_int16_t yy_chk[820] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    4,    5,    6,   19,    5,
        6,   18,  255,   18,   18,   18,   23,   23,   20,   19,
       20,   20,   20,   35,   26,   61,  254,   26,   61,  102,

       29,  251,   20,   27,  250,   29,   35,   33,   26,   19,
       39,  247,   27,   38,   33,   42,   19,  102,   29,   35,
       26,    5,    6,   26,   38,   27,  102,   29,   33,   20,
       27,   29,   39,   69,   33,   19,  245,   39,   27,   38,
       33,   42,   42,   75,   69,    3,    4,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   69,
       31,   40,   12,   12,   12,   12,   12,  244,   28,   75,
       75,   28,  243,   31,  239,   28,  129,  129,   31,   78,
       30,   28,   30,   40,  235,   78,   31,   31,   40,  233,
       12,   12,   12,   12,   28,   28,   30,   34,   28,   31,

       36,   34,   28,   68,   31,   78,   30,   28,   30,   36,
       79,   37,   60,   60,   60,   76,   12,   12,  232,   34,
       79,   37,   36,   37,   34,   41,   68,   36,   34,   76,
       68,   41,   37,   41,  223,   36,   79,  221,   37,  219,
       41,   76,   43,   43,   41,   72,   87,   37,   71,   37,
       43,  218,   41,   59,   59,   59,   87,   41,   72,   41,
       63,   43,   63,   63,   63,   59,   41,   81,   71,   43,
       43,   72,   87,  217,   63,   71,   43,   54,   82,   64,
       54,   64,   73,   81,   64,   64,   64,  181,  181,   82,
       77,   80,   59,   81,   73,   73,   74,   77,   83,   54,

      211,   63,   85,   54,   82,   73,   88,  209,   74,   73,
       54,   85,   83,   54,   80,   54,   77,   54,   80,   74,
       73,   73,   54,   74,   83,  208,   54,   97,   85,   88,
       54,   86,   93,   88,   74,  207,   54,   94,   90,   54,
       89,   54,  205,   54,   57,   86,   89,   90,   57,   97,
       94,   93,   96,  154,   97,   57,  204,   86,   57,   93,
       57,   96,   57,   94,   90,   95,   89,   95,   57,   99,
      100,   57,  101,  154,  200,   57,  103,   99,   96,  104,
      154,   57,  100,  101,   57,  103,   57,  130,   57,  130,
      130,   95,   95,  137,   95,   99,  100,  104,  101,  127,

      127,  127,  103,  128,  139,  128,  104,  140,  128,  128,
      128,  133,  133,  133,  135,  135,  135,  141,  194,  137,
      137,  143,  139,  140,  144,  147,  145,  148,  191,  141,
      190,  139,  150,  140,  185,  144,  145,  152,  153,  147,
      141,  151,  150,  143,  141,  184,  159,  151,  143,  148,
      144,  147,  145,  155,  148,  141,  164,  167,  150,  160,
      153,  152,  155,  160,  152,  153,  165,  151,  159,  161,
      164,  162,  166,  159,  163,  168,  161,  158,  170,  155,
      157,  169,  164,  160,  162,  156,  160,  170,  165,  188,
      160,  168,  161,  165,  166,  149,  161,  162,  146,  166,

      169,  168,  161,  188,  170,  178,  178,  178,  169,  180,
      180,  180,  182,  182,  183,  188,  183,  183,  186,  186,
      186,  187,  189,  142,  192,  187,  193,  196,  198,  195,
      138,  197,  199,  192,  201,  193,  136,  202,  214,  214,
      197,  199,  132,  210,  189,  201,  126,  187,  198,  189,
      192,  195,  193,  196,  196,  198,  195,  197,  199,  202,
      201,  203,  206,  212,  202,  210,  213,  213,  213,  220,
      210,  222,  203,  206,  215,  215,  216,  216,  224,  226,
      225,  227,  229,  125,  222,  212,  228,  203,  206,  224,
      212,  230,  228,  231,  124,  220,  220,  222,  225,  234,

      227,  226,  237,  236,  224,  229,  226,  225,  227,  229,
      238,  240,  228,  234,  241,  237,  231,  230,  230,  242,
      231,  238,  241,  246,  249,  234,  236,  123,  237,  240,
      236,  248,  252,  253,  242,  249,  238,  246,  240,  122,
      241,  248,  121,  119,  107,  242,  105,   98,   92,  246,
      249,   91,   84,   67,  252,  253,   62,  248,   56,  252,
      253,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  257,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  260,  260,  260,  260,  260,  261,  261,  262,

       55,  262,  262,  262,  262,  262,  262,  262,  262,  263,
       50,  263,   32,  263,  263,  263,  263,  263,  263,  263,
      264,   25,  264,   21,  264,  264,  264,  264,  264,  265,
        7,  265,  265,  266,  266,  266,  266,  267,  267,  267,
      268,  268,  268,  268,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,

      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[91] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#line 2 "lexer.l"
//include "lexer.h"		//use to run flex standalone
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <stdbool.h>
#include <math.h>
#include <string.h>
#include "parser.tab.h" 
#include "settings.h"

int error_count = 0;
char str_buffer[256]; //restrict strings to 256 chars
char *str_buf_ptr;
char cconst_buffer[3];
char *s;							//pointer to emulate fflush

void Keyword_Print(char *keyword_id);
void CCONST_Print(char *token);
void CCONST_Print1(char token);
void Token_Print(char *t);
void Number_Print(int base);
void double_print(int base);
int string_to_int(char *str);
int HexToInt(char *str);
int BinToInt(char *str);
float HexToDouble(char *str);
float BinToDouble(char *str);
void yyerror(const char *err);
#line 768 "lex.yy.c"
/* INITIAL STATES */

#line 771 "lex.yy.c"

#define INITIAL 0
#define COMMENT 1
#define STRING 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 55 "lexer.l"


#line 993 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 257 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 745 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 57 "lexer.l"
{Keyword_Print("PROGRAM"); return T_PROGRAM;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 58 "lexer.l"
{Keyword_Print("CONST"); return T_CONST;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 59 "lexer.l"
{Keyword_Print("TYPE"); return T_TYPE;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 60 "lexer.l"
{Keyword_Print("ARRAY"); return T_ARRAY;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 61 "lexer.l"
{Keyword_Print("LIST"); return T_LIST;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 62 "lexer.l"
{Keyword_Print("SET"); return T_SET;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 63 "lexer.l"
{Keyword_Print("OF"); return T_OF;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 64 "lexer.l"
{Keyword_Print("RECORD"); return T_RECORD;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 65 "lexer.l"
{Keyword_Print("VAR"); return T_VAR;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 66 "lexer.l"
{Keyword_Print("FUNCTION"); return T_FUNCTION;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 67 "lexer.l"
{Keyword_Print("PROCEDURE"); return T_PROCEDURE;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 68 "lexer.l"
{Keyword_Print("INTEGER"); return T_INTEGER;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 69 "lexer.l"
{Keyword_Print("REAL"); return T_REAL;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 70 "lexer.l"
{Keyword_Print("BOOLEAN"); return T_BOOLEAN;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 71 "lexer.l"
{Keyword_Print("CHAR"); return T_CHAR;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 72 "lexer.l"
{Keyword_Print("FORWARD"); return T_FORWARD;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 73 "lexer.l"
{Keyword_Print("LENGTH"); return T_LENGTH;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 74 "lexer.l"
{Keyword_Print("NEW"); return T_NEW;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 75 "lexer.l"
{Keyword_Print("BEGIN"); return T_BEGIN;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 76 "lexer.l"
{Keyword_Print("END"); return T_END;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 77 "lexer.l"
{Keyword_Print("IF"); return T_IF;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 78 "lexer.l"
{Keyword_Print("THEN"); return T_THEN;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 79 "lexer.l"
{Keyword_Print("ELSE"); return T_ELSE;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 80 "lexer.l"
{Keyword_Print("WHILE"); return T_WHILE;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 81 "lexer.l"
{Keyword_Print("DO"); return T_DO;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 82 "lexer.l"
{Keyword_Print("CASE"); return T_CASE;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 83 "lexer.l"
{Keyword_Print("OTHERWISE"); return T_OTHERWISE;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 84 "lexer.l"
{Keyword_Print("FOR"); return T_FOR;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 85 "lexer.l"
{Keyword_Print("TO"); return T_TO;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 86 "lexer.l"
{Keyword_Print("DOWNTO"); return T_DOWNTO;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 87 "lexer.l"
{Keyword_Print("WITH"); return T_WITH;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 88 "lexer.l"
{Keyword_Print("READ"); return T_READ;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 89 "lexer.l"
{Keyword_Print("WRITE"); return T_WRITE;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 92 "lexer.l"
{Token_Print("OROP"); return T_OROP;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 93 "lexer.l"
{Token_Print("NOTOP"); return T_NOTOP;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 94 "lexer.l"
{Token_Print("INOP"); return T_INOP;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 97 "lexer.l"
{printf("Found BOOLEAN -> %s",yytext); return T_BCONST;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 99 "lexer.l"
{printf("Found LISTFUNC -> %s",yytext); return T_LISTFUNC;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 101 "lexer.l"
{Token_Print("RELOP"); return T_RELOP;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 102 "lexer.l"
{Token_Print("ADDOP"); return T_ADDOP;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 103 "lexer.l"
{Token_Print("MULDIVANDOP"); return T_MULDIVANDOP;}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 105 "lexer.l"
{Token_Print("T_EOF"); yylval.strval = strdup(yytext); return T_EOF;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 107 "lexer.l"
{Token_Print("ID"); yylval.strval = strdup(yytext); return T_ID;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 112 "lexer.l"
{double_print(10); yylval.realval = atof(yytext); return T_RCONST;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 114 "lexer.l"
{double_print(10); yylval.realval = atof(yytext); return T_RCONST;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 116 "lexer.l"
{double_print(16); yylval.realval = HexToDouble(yytext); return T_RCONST;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 118 "lexer.l"
{double_print(2); yylval.realval = BinToDouble(yytext); return T_RCONST;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 120 "lexer.l"
{Number_Print(10); yylval.intval = atoi(yytext); return T_ICONST;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 122 "lexer.l"
{Number_Print(16); yylval.intval = HexToInt(yytext); return T_ICONST;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 124 "lexer.l"
{Number_Print(2); yylval.intval = BinToInt(yytext); return T_ICONST;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 127 "lexer.l"
{strcpy(cconst_buffer, "\\n"); CCONST_Print(cconst_buffer); yylval.strval = strdup(cconst_buffer); return T_CCONST;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 128 "lexer.l"
{strcpy(cconst_buffer, "\\f"); CCONST_Print(cconst_buffer); yylval.strval = strdup(cconst_buffer); return T_CCONST;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 129 "lexer.l"
{strcpy(cconst_buffer, "\\t"); CCONST_Print(cconst_buffer); yylval.strval = strdup(cconst_buffer); return T_CCONST;}	
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 130 "lexer.l"
{strcpy(cconst_buffer, "\\r"); CCONST_Print(cconst_buffer); yylval.strval = strdup(cconst_buffer); return T_CCONST;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 131 "lexer.l"
{strcpy(cconst_buffer, "\\b"); CCONST_Print(cconst_buffer); yylval.strval = strdup(cconst_buffer); return T_CCONST;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 132 "lexer.l"
{strcpy(cconst_buffer, "\\v"); CCONST_Print(cconst_buffer); yylval.strval = strdup(cconst_buffer); return T_CCONST;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 134 "lexer.l"
{CCONST_Print1(yytext[1]); yylval.charval = yytext[1]; return T_CCONST;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 135 "lexer.l"
{CCONST_Print1(yytext[1]); yylval.charval = yytext[1]; return T_CCONST;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 138 "lexer.l"
{BEGIN(STRING); str_buf_ptr = str_buffer;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 139 "lexer.l"
{BEGIN(INITIAL); *str_buf_ptr = '\0';
                                yylval.strval = strdup(str_buffer); 
                                printf("\nFound String -> %s | TOKEN NUMBER: %d | LINE: %d\n", str_buffer, T_STRING, yylineno);
                                return (T_STRING);}
	YY_BREAK
case 60:
/* rule 60 can match eol */
YY_RULE_SETUP
#line 143 "lexer.l"
{yyerror("Illegal input in string"); exit(1);}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 144 "lexer.l"
{*str_buf_ptr++ = '\n';}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 145 "lexer.l"
{*str_buf_ptr++ = '\f';}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 146 "lexer.l"
{*str_buf_ptr++ = '\t';}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 147 "lexer.l"
{*str_buf_ptr++ = '\r';}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 148 "lexer.l"
{*str_buf_ptr++ = '\b';}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 149 "lexer.l"
{*str_buf_ptr++ = '\v';}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 150 "lexer.l"
{*str_buf_ptr++ = '\\';}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 151 "lexer.l"
{*str_buf_ptr++ = '"';}
	YY_BREAK
case 69:
/* rule 69 can match eol */
YY_RULE_SETUP
#line 152 "lexer.l"
{ printf("\nMultiple line string!\n"); } 
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 153 "lexer.l"
{*str_buf_ptr++ = yytext[1];}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 154 "lexer.l"
{char *yptr = yytext;
                                while(*yptr) *str_buf_ptr++ = *yptr++;
                            }
	YY_BREAK
case YY_STATE_EOF(STRING):
#line 157 "lexer.l"
{yyerror("EOF in String"); exit(1);}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 162 "lexer.l"
{s=str_buffer; BEGIN(COMMENT);}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 163 "lexer.l"
{*s='\0'; printf("\nFound Comment\n"); BEGIN(INITIAL);}
	YY_BREAK
case 74:
/* rule 74 can match eol */
YY_RULE_SETUP
#line 164 "lexer.l"
{ printf("\nMultiple line Comment!\n"); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 165 "lexer.l"
{}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 170 "lexer.l"
{Token_Print("LPAREN"); return T_LPAREN;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 171 "lexer.l"
{Token_Print("RPAREN"); return T_RPAREN;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 172 "lexer.l"
{Token_Print("SEMI"); return T_SEMI;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 173 "lexer.l"
{Token_Print("DOT"); return T_DOT;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 174 "lexer.l"
{Token_Print("COMMA"); return T_COMMA;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 175 "lexer.l"
{Token_Print("EQU"); return T_EQU;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 176 "lexer.l"
{Token_Print("COLON"); return T_COLON;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 177 "lexer.l"
{Token_Print("LBRACK"); return T_LBRACK;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 178 "lexer.l"
{Token_Print("RBRACK"); return T_RBRACK;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 179 "lexer.l"
{Token_Print("ASSIGN"); return T_ASSIGN;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 180 "lexer.l"
{Token_Print("DOTDOT"); return T_DOTDOT;}
	YY_BREAK
case 87:
/* rule 87 can match eol */
YY_RULE_SETUP
#line 182 "lexer.l"
{printf("\n[Line %d]\n",yylineno);}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 183 "lexer.l"
{}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 184 "lexer.l"
{yyerror("Unrecognised character");}
	YY_BREAK
case YY_STATE_EOF(COMMENT):
#line 185 "lexer.l"
{printf("\nEOF\n"); return T_EOF;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 188 "lexer.l"
ECHO;
	YY_BREAK
#line 1531 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 257 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 257 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 256);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 188 "lexer.l"


void Keyword_Print(char *keyword_id){printf("\nKEYWORD -> %s\n",keyword_id);}

void Token_Print(char *token){printf("\nFound token %s -> %s\n",token,yytext);}

void CCONST_Print(char *token){printf("\nFound CCONST -> %s\n", token);}

void CCONST_Print1(char token){printf("\nFound CCONST -> %c\n", token);}

int BinToInt(char *str){ return (int) strtol(&str[2], NULL, 2); }

int HexToInt(char *str){ return (int) strtol(&str[2], NULL, 16); }

float HexToDouble(char* str){
    float number = 0.0;
    int i,length_real;
    char *character;
    character = strchr(str,'.');
    length_real = strlen(character)-1;
    number = (int)strtol(&str[2],&character,16);
    for(i=1;i<=length_real;i++){
        if(character[i] <= '9'){
            number += (character[i] - '0') * (1/pow(16,i));
        }else{
            number += (character[i] + 10 - 'A') * (1/pow(16,i)); /** TODO: CASE SENSITIVE **/
        }
    }
    return number;
}

float BinToDouble(char* str){
    float number = 0.0;
    int i,length_real;
    char *character;
    character = strchr(str,'.');
    length_real = strlen(character)-1;
    number = (int)strtol(&str[2],&character,2);
    for(i=1;i<length_real;i++){
        number += (character[i] - '0') * (1/pow(2,i));
    }
    return number;
}

void double_print(int base){
    float number;
    if(base==16){
		number=HexToDouble(yytext);
    }else if(base==2){
        number=BinToDouble(yytext);
    }else{
		number=atof(yytext);
	}
    printf("\nRCONST FOUND: %lf (%s)\n",number,yytext);
}

void Number_Print(int base){
	int number;
    if(base==16){
		number=HexToInt(yytext);
    }else if(base==2){
        number=BinToInt(yytext);
    }else{
		number=atoi(yytext);
	}
	printf("\nICONST FOUND: %d (%s)\n",number,yytext);
}

void yyerror(const char* err) {

    error_count++;

    fprintf(stderr, "\n[ERROR - Line %d]: %s\n", yylineno, err);

    if (error_count == MAX_ERRORS) {
        printf("\nError count limit reached. Exiting...\n");
        fprintf(stderr, "\nError limit reached!\n");
        exit(EXIT_FAILURE);
    }

}

